### ISSUE TITLE
EnvironmentError: mysql_config not found

### ISSUE THREAD

**Issue by tanmayAccela** [cphsolutionslab/ckanext-dataproxy#1]
While installing the requirements, following error is thrown:

File "--/ckan/lib/default/build/MySQL-python/setup.py", line 17, in <module>

```
metadata, options = get_config()
```

  File "setup_posix.py", line 43, in get_config

```
libs = mysql_config("libs_r")
```

  File "setup_posix.py", line 25, in mysql_config

```
raise EnvironmentError("%s not found" % (mysql_config.path,))
```

EnvironmentError: mysql_config not found

What is expected in mysql_config ?

**Comment by ozooner** [comment]
Hi, which version of CKAN are you using?
The module is tested & developed on 2.2.1.
(2.2.1 does not have ckan/lib/default folder)

Other than that, MySQL driver setup should not be related to CKAN whatsoever...

**Comment by tanmayAccela** [comment]
I am using 2.2.1. According to requirements, if using dataproxy with MySQL database(s), we need to install MySQL-python==1.2.5. And then I get the mentioned error. I tested the plugin and it worked perfectly fine with PostgreSQL and not with MySQL and MS-SQL.

**Comment by tanmayAccela** [comment]
http://stackoverflow.com/questions/5178292/pip-install-mysql-python-fails-with-environmenterror-mysql-config-not-found solved the issue. Closing this.
