### ISSUE TITLE
Hide hashed database password

### ISSUE THREAD

**Issue by beechnut** [cphsolutionslab/ckanext-dataproxy#11]
The database password, while securely hashed, is shown in "Additional Information" in the resource view. We should removed this attribute from the view.

(Also, we should cast the port number to a string -- it's currently formatted as a number.)

![screen shot 2015-03-26 at 6 20 42 pm](https://cloud.githubusercontent.com/assets/1887182/6858519/95df447e-d3e5-11e4-90c3-4ee7e291d79c.png)

**Comment by ozooner** [comment]
Removing db_password in before_show hook
