### ISSUE TITLE
dataproxy is not working

### ISSUE THREAD

**Issue by youkad** [cphsolutionslab/ckanext-dataproxy#15]
Hello,
I want to test this ckan extension for connecting ckan to databases. I follow the steps of installation on https://github.com/cphsolutionslab/ckanext-dataproxy
It is installed without errors but I cannot see the plugging on the ckan interface.
Am I missing something for a complete installation of this extension?
Thanks.

**Comment by tanmayAccela** [comment]
Make sure to add it to plugins like:
ckan.plugins = stats text_preview ... dataproxy 

And restart the server.

**Comment by youkad** [comment]
I did a package installation of ckan version 2.4, I installed ckanext-dataproxy according to the steps on https://github.com/cphsolutionslab/ckanext-dataproxy, I restart the server like you mention.
But when I want to Add a dataset I cannot see the dataproxy button. I am confused if I need other plugins or just the installation of dataproxy doesn't run correctly.
Thanks a lot.

**Comment by reederz** [comment]
@youkad any errors in the server log or javascript console?

**Comment by reederz** [comment]
@ozooner is it supposed to work on v2.4?

**Comment by ozooner** [comment]
@youkad, the master branch is v2.2 compatible and will not work with ckan 2.3, therefore it is strong evidence that it will not also work with 2.4. However could try cloning 'v2.3' branch instead, but I can not guarantee that it works with newer version as I haven't tested it. If you're interested in 2.4 compatibility, we can discuss it via e-mail ss@fadeit.dk
