### ISSUE TITLE
Working Version for CKAN 2.5.2

### ISSUE THREAD

**Issue by jfabeel** [cphsolutionslab/ckanext-dataproxy#16]
Is there any plans for an update to get this extension to work with the newest version of CKAN 2.5.2? What needs to be changed so that this extension will work. I found this extension to be extremely valuable. Thank you!

**Comment by reederz** [comment]
@jfabeel yes, we should have it within the next couple of weeks.

**Comment by reederz** [comment]
Compatibility done.
