### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by german-bortoli** [cphsolutionslab/ckanext-dataproxy#19]
Hello I am using ckan 2.6 and am trying to install it but I am getting the following error.

<blockquote>
/src/MD2.o
    src/MD2.c:31:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Command "/usr/lib/ckan/default/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-vLuVml/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-rMmJkZ-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/lib/ckan/default/include/site/python2.7/pycrypto" failed with error code 1 in /tmp/pip-build-vLuVml/pycrypto
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

</blockquote>

**Comment by reederz** [comment]
You're most likely missing `python-dev` package if you're using Ubuntu (or similar package on another distro). A simple web search should reveal the answer.
